### ISSUE TITLE
Match invitation deadline with the webfield deadline string

### ISSUE THREAD

**Issue by melisabok** [iesl/openreview-scripts#419]
We need to keep the same value in a single place. 

It happened that these fields didn't match in two conferences today. 

I think the solution is to save a single value(timestamp) and then decide which timezone to use to render the deadline in the webfield. So we can avoid the inconsistency of the dates.

**Comment by mspector** [comment]
I have a question about this: does the duedate field in the invitation stop users from submitting to it, or does it only control the display of the duedate?

If it does prevent users from submitting, we may actually want to keep them separate, so that the enforced deadline (the duedate in the invitation field) is different from the displayed deadline (in the webfield). Program chairs often want to do this, for example, if they want to give the authors a 15 minute grace period, but want a hard deadline 15 minutes later.

If they are both cosmetic changes, then I agree that there's no reason to have them in different places.

**Comment by pmandler** [comment]
Fixed  by using duedate and expdate.
